# Generated by Django 5.2.1 on 2025-05-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Product_images/')),
                ('model_number', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('warranty_date', models.DateField()),
                ('device_name', models.CharField(max_length=100)),
            ],
        ),
    ]
