# Generated by Django 5.2.1 on 2025-05-17 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='device_name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='model_number',
            new_name='product_model_number',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
    ]
